language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="8.0" UNIT_TEST="1" ODOO_REPO="odoo/odoo" LINT_CHECK="1"

virtualenv:
  system_site_packages: true

# install dependencies
install:
  - pip install -r requirements.txt
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

# create DB
#before_script:
#  - ./install-odoo.sh
#  - createdb test

script:
  - travis_run_tests

