language: python

python:
  - "2.7"

env:
  - ODOO="https://github.com/odoo/odoo/archive/8.0.tar.gz"

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install ${ODOO}

# create DB
before_script:
#  - ./install-odoo.sh
  - createdb test

script:
  - odoo.py -d test --stop-after-init --init=$(python -c 'import os; print(",".join(x for x in os.listdir(".") if os.path.isdir(x) and not x.startswith(".")))') --addons-path=$(pwd),`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`/addons

