language: python
python:
  - "2.7"
env:
  - VERSION="8.0" UNIT_TEST="1" ODOO_REPO="odoo/odoo" LINT_CHECK="1"

virtualenv:
  system_site_packages: true

# install dependencies
install:
  - pip install -r requirements.txt
  - git clone https://github.com/amdeb/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

# create DB
#before_script:
#  - ./install-odoo.sh
#  - createdb test

script:
  - travis_run_tests

